### ISSUE TITLE
Format: flowed

### ISSUE THREAD

**Issue by theohonohan** [breck7/breckyunits.com#1]
You mention the "haiku" problem which arose when you sent emails with short lines.

You might be aware of an interesting attempt to fix this: "Format: flowed". It's specified in a number of RFCs including this one: https://datatracker.ietf.org/doc/html/rfc3676

Further discussion here:
https://fastmail.blog/advanced/format-flowed/

You might find that you can steal some ideas from "Format: flowed", specifically ways of achieving soft line wrapping in plaintext formats.

**Comment by breck7** [comment]
Interesting! I don't think I ever saw format=flowed. Thank you for bringing it to my attention.

>  specifically ways of achieving soft line wrapping in plaintext formats.

Do you have any favorite techniques?

**Comment by theohonohan** [comment]
I haven't given these things a lot of thought recently, but distinguishing
between " \n" and "\n" at the end of a line seemed like quite a good idea
when I first encountered it.

It's really what would happen automatically if an editor wrapped a long
line, which is the beauty of it, I think.

**Comment by breck7** [comment]
I can't think of any immediate action item now, so going to close this out, but thanks for expanding my mind on this issue!
