### ISSUE TITLE
Comment on "Words are Worse than Weights" post

### ISSUE THREAD

**Issue by celtic-coder** [breck7/breckyunits.com#4]
Hi Breck(@breck7),

How are you keeping?

I was looking at your [latest scroll](https://github.com/breck7/breckyunits.com/blob/c397242ff7cb23e76ebd478298dc22b7e69db871/wordsAreWorseThanWeights.scroll) and just wanted to say that it is an interesting perspective on what is currently happening in AI.

My wife also believes in the power of words. She is a wordsmith and enjoys crafting short stories and poetry. I can therefore understand your perspective on the power and necessity of the right use of words. However, it is disheartening to see this approaching tsunami which will overpower what for centuries was our main tool for communication and learning and expression.

We are all wrestling with addressing the question of what will come next? I trust that you will find something that is fulfilling and satisfying.

Kind Regards,
Liam

**Comment by breck7** [comment]
Hi @celtic-coder! Sorry for the late reply. Been deep in thought!

Thank you for the comments on the Words are Worse than Weights post.

I have evolved from that line of thinking to something new. Hope to share more soon.

Best,
Breck

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

That would be interesting - looking forward to whatever insights you might share.

Kind Regards,
Liam
